title: "Crypto Docker Stack"
description: "An all in one Docker stack for installing bitcoin-core, electrs, their relevant web-ui's from Umbrel and a mempool explorer."
theme: "jekyll-theme-modernist"
locale: "en"
name: "JDsnyke"
