version: "3.7"

services:
  whoogle:
    container_name: whoogle
    image: benbusby/whoogle-search:0.8.3
    restart: unless-stopped
    stop_grace_period: 1m
    ports:
      - "6420:6420"
    environment:
      EXPOSE_PORT: "6420"
    networks:
      default:
        ipv4_address: "10.21.22.10"
  dashdot:
    container_name: dashdot
    image: mauricenino/dashdot:sha-4bef01c
    restart: unless-stopped
    privileged: true
    ports:
      - "3001:3001"
    environment:
      DASHDOT_SHOW_DASH_VERSION: "icon_hover"
      DASHDOT_ENABLE_CPU_TEMPS: "true"
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: "true"
      DASHDOT_ACCEPT_OOKLA_EULA: "true"
    volumes:
      - ./extras/dashdot:/mnt/host:ro
    networks:
      default:
        ipv4_address: "10.21.22.11"
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    ports:
      - "7575:7575"
    environment:
      TZ: "Europe/Paris"
    volumes:
      - ./extras/homarr/configs:/app/data/configs
      - ./extras/homarr/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        ipv4_address: "10.21.22.13"
