version: "3.7"

services:
  tor:
    container_name: tor
    image: lncm/tor:0.4.7.13
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ../volumes/tor/torrc/torrc:/etc/tor/torrc:ro
      - ../volumes/tor/data:/data
    environment:
      HOME: "/tmp"
    networks:
      default:
        ipv4_address: "${APP_TOR_IP}"
  i2pd:
    container_name: i2pd
    image: purplei2p/i2pd:release-2.50.2
    user: "root"
    command: --sam.enabled=true --sam.address=0.0.0.0 --sam.port=${APP_I2PD_PORT} --loglevel=error
    restart: on-failure
    volumes:
      - ../volumes/i2pd:/home/i2pd/data
    networks:
      default:
        ipv4_address: "${APP_I2PD_IP}"
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "${APP_NETWORK_SUBNET}"
