version: "3.7"

services:
  whoogle:
    container_name: whoogle
    image: benbusby/whoogle-search:0.8.3
    restart: unless-stopped
    stop_grace_period: 1m
    ports:
      - "6420:6420"
    environment:
      EXPOSE_PORT: "6420"
    networks:
      default:
        ipv4_address: "10.21.22.10"
  dashdot:
    container_name: dashdot
    image: mauricenino/dashdot:sha-4bef01c
    restart: unless-stopped
    privileged: true
    ports:
      - "3001:3001"
    environment:
      DASHDOT_SHOW_DASH_VERSION: "icon_hover"
      DASHDOT_ENABLE_CPU_TEMPS: "true"
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: "true"
      DASHDOT_ACCEPT_OOKLA_EULA: "true"
    volumes:
      - ./extras/dashdot:/mnt/host:ro
    networks:
      default:
        ipv4_address: "10.21.22.11"
  snapdrop:
    container_name: snapdrop
    image: linuxserver/snapdrop:version-eac78009
    restart: on-failure
    ports:
      - "8085:80"
    environment:
      PUID: "1000"
      PGID: "1000"
    volumes:
      - ./extras/snapdrop:/config
    networks:
      default:
        ipv4_address: "10.21.22.12"
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    ports:
      - "7575:7575"
    environment:
      TZ: "Europe/Paris"
    volumes:
      - ./extras/homarr/configs:/app/data/configs
      - ./extras/homarr/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        ipv4_address: "10.21.22.13"
  lightning_gui:
    container_name: lightning_gui
    image: getumbrel/umbrel-lightning:v1.1.2
    restart: on-failure
    environment:
      PORT: "3006"
      TOR_PROXY_IP: "${APP_TOR_IP}"
      TOR_PROXY_PORT: "9050"
      BITCOIN_HOST: "${APP_BITCOIND_IP}"
      RPC_PORT: "8332"
      RPC_USER: "${APP_BITCOIN_RPC_USERNAME}"
      RPC_PASSWORD: "${APP_BITCOIN_RPC_PASSWORD}"
      LND_NETWORK: "mainnet"
      LND_HOST: "${APP_LIGHTNING_NODE_IP}"
      LND_REST_HIDDEN_SERVICE: "${APP_LIGHTNING_REST_SERVICE}"
      LND_GRPC_HIDDEN_SERVICE: "${APP_LIGHTNING_RPC_SERVICE}"
      TLS_FILE: "/data/.lnd/tls.cert"
      MACAROON_DIR: "/data/.lnd/data/chain/bitcoin/mainnet/"
      CHANNEL_BACKUP_FILE: "/data/.lnd/data/chain/bitcoin/mainnet/channel.backup"
      BACKUP_STATUS_FILE: "/statuses/backup-status.json"
      JSON_STORE_FILE: "/data/state.json"
      JSON_SETTINGS_FILE: "/data/settings.json"
      UMBREL_LND_CONF_FILEPATH: "/data/.lnd/umbrel-lnd.conf"
      LND_CONF_FILEPATH: "/data/.lnd/lnd.conf"
      DEVICE_DOMAIN_NAME: "${DEVICE_DOMAIN_NAME}"
      EXPLORER_PORT: "3002"
      EXPLORER_HIDDEN_SERVICE: "${APP_MEMPOOL_HIDDEN_SERVICE}"
    volumes:
      - "${APP_LIGHTNING_NODE_DATA_DIR}:/data/.lnd" # TODO
      - "${APP_DATA_DIR}/data/lightning:/data"
      - "${UMBREL_ROOT}/statuses:/statuses"
    networks:
      default:
        ipv4_address: "10.21.22.15"
  pihole:
    container_name: pihole
    image: pihole/pihole:2023.10.0
    restart: on-failure
    network_mode: host
    environment:
      VIRTUAL_HOST: "${DEVICE_DOMAIN_NAME}"
      WEBPASSWORD: "piholepassword"
      WEB_PORT: "8082"
      DNSMASQ_LISTENING: "all"
    volumes:
      - ./extras/pihole/pihole:/etc/pihole
      - ./extras/pihole/dnsmasq:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:v1.50.1
    restart: on-failure
    network_mode: "host"
    stop_grace_period: 1m
    command: "sh -c 'tailscale web --listen 0.0.0.0:8240 & exec tailscaled --tun=userspace-networking'"
    volumes:
      - ./extras/tailscale:/var/lib
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
